packages:
  - "apps/*"
  - "packages/*"
allowBuilds:
  esbuild: true
  sharp: true
minimumReleaseAgeExclude:
  - expo-dev-client@57.0.8
  - expo-dev-launcher@57.0.8
  - expo-dev-menu@57.0.8
  - expo-constants@57.0.7
